### ISSUE TITLE
Change the value of AuthnCacheContext? 

### ISSUE THREAD

**Issue by ghost** [sspreitzer/docker-httpd-mirror#2]
Thanks for providing the container! I have a question about one httpd config:`AuthnCacheContext`.
It seems the [official document](https://httpd.apache.org/docs/current/mod/mod_authn_socache.html#authncachecontext) recommends to change the default `directory`, which is conservative and not optimal. **A better policy is to name the `AuthnCacheContext` for the password provider: for example a htpasswd file or database table.**

Maybe it's better to set that to specify a context string for use in the cache keyin the comfig file? Thanks.

**Comment by sspreitzer** [comment]
Hi @HCHCHH 

I am using the centos:7 as the base docker image and the httpd package.
Please raise your request to the upstream vendor, which is Red Hat.
https://bugzilla.redhat.com

PS.: You can also reuse this image as a base and tweak the changes you like to have.

Because the feature request is destined for upstream, I will close this issue.

Kind regards
Sascha
